app/weather/models.py
from peewee import *
from app.base_model import BaseModel
from app.auth.models import UserAuth


class Country(BaseModel):
    code = CharField(max_length=2, unique=True, index=True)
    name = CharField(max_length=100, unique=True, index=True)


class Capital(BaseModel):
    name = CharField(max_length=150, unique=True, index=True)
    country = ForeignKeyField(Country, backref='capital')


class City(BaseModel):
    name = CharField(max_length=100, unique=True, index=True)
    country = ForeignKeyField(Country, backref='city')


class UserCities(BaseModel):
    user_id = ForeignKeyField(UserAuth, backref='user_city')
    city_id = ForeignKeyField(City, backref='user_city')

app/weather/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Optional


class GenerateCapitalsForm(FlaskForm):
    submit = SubmitField('Generate')


class WeatherForm(FlaskForm):
    city = StringField(
        'Write city name.',
        validators=[DataRequired(), Length(2, 100)],
        render_kw={'placeholder': 'City name'}
    )

    submit = SubmitField('Get weather')


class AddCityForm(FlaskForm):
    country = StringField(
        'Write country name.',
        validators=[Optional(), Length(2, 100)],
        render_kw={'placeholder': 'Country name'},
    )
    city = StringField(
        'Write city name.',
        validators=[DataRequired(), Length(2, 100)],
        render_kw={'placeholder': 'City name'}
    )

    submit = SubmitField('Add city')

app/api/weather/capitals/__init__.py
from flask_restful import Api
from flask import current_app

from app.api.weather.capitals.capital import CapitalName
from app.api.weather.capitals.capitals import Capitals

# /api/v1/capitals/
# /api/v1/capitals/<city_id>/
# GET = all_cities 200
# POST = add city 201
# PUT = update_cities 204
# DELETE = delete_all_cities 204


def init_app(app):
    with app.app_context():
        api = Api(app, decorators=[current_app.config['CSRF'].exempt])
        api.add_resource(CapitalName, f'/api/v1/capitals/<capital_id>')
        api.add_resource(Capitals, f'/api/v1/capitals/')

app/api/weather/cities/__init__.py
from flask_restful import Api
from flask import current_app

from app.api.weather.cities.city import CityName
from app.api.weather.cities.cities import Cities

# /api/v1/cities/
# /api/v1/cities/<city_id>/
# GET = all_cities 200
# POST = add city 201
# PUT = update_cities 204
# DELETE = delete_all_cities 204


def init_app(app):
    with app.app_context():
        api = Api(app, decorators=[current_app.config['CSRF'].exempt])
        api.add_resource(CityName, f'/api/v1/cities/<city_id>')
        api.add_resource(Cities, '/api/v1/cities/')

app/api/weather/countries/__init__.py
from flask_restful import Api
from flask import current_app

from app.api.weather.countries.country import CountryName
from app.api.weather.countries.countries import Countries


# /api/v1/countries/
# /api/v1/countries/1
# GET = all_cities 200
# POST = add city 201
# PUT = update_cities 204
# DELETE = delete_all_cities 204


def init_app(app):
    with app.app_context():
        api = Api(app, decorators=[current_app.config['CSRF'].exempt])
        api.add_resource(CountryName, '/api/v1/countries/<country_id>')
        api.add_resource(Countries, '/api/v1/countries/')

app/weather/__init__.py
from flask import Blueprint

weather = Blueprint('weather', __name__, url_prefix='/weather')

from app.weather import routes

app/weather/routes.py
"""Routes for app 'weather'."""
from flask import render_template, redirect, url_for, flash, request
from datetime import datetime

from flask_login import login_required, current_user
from flask_paginate import Pagination
from peewee import DoesNotExist, IntegrityError
from random import randint

from app.weather import weather
from app.weather.forms import WeatherForm, AddCityForm, GenerateCapitalsForm
from app.weather.models import Capital, City, Country, UserCities
from app.auth.models import UserAuth
from app.weather.handlers.get_weather_for_cities import get_weather_for_cities
from app.weather.handlers.get_weather_for_user_cities import get_weather_for_user_cities
from app.handlers.get_qty_position_per_page import get_qty_position_per_page

from utils.weather.getting_weather import main as getting_weather
from utils.weather.getting_weather import main as get_weather
from utils.weather.getting_forecast_5d import main as getting_forecast_5d
from utils.weather.generate_data.generate_cities import get_ua_cities, get_cities_for_5_country
from utils.weather.generate_data.generate_data_capitels import main as generate_capitals


@weather.route('/home', methods=['POST', 'GET'])
@login_required
def index():
    """Weather page."""
    form = WeatherForm()

    if not form.city.data:
        return render_template(
            'weather/index.html',
            title='Home page',
            current_time=datetime.utcnow(),
            form=form
            )

    city = form.city.data
    weather_in_city = get_weather(city)
    if 'error' in weather_in_city:
        flash(f"{weather_in_city['error']} - ({city}).")
        return redirect(url_for('weather.index'))

    form.city.data = ''
    return render_template(
        'weather/index.html',
        title='Home page',
        current_time=datetime.utcnow(),
        form=form,
        weather=weather_in_city
        )


@weather.route('/add/city', methods=['POST', 'GET'])
@login_required
def add_city():
    """Add city."""
    form = AddCityForm()

    if form.validate_on_submit():
        country = form.country.data
        city = form.city.data

        weather_in_city = get_weather(city)
        if 'error' in weather_in_city:
            flash(f"{weather_in_city['error']} - ({city}).")
            return redirect(url_for('weather.index'))

        message = f'City "{city.capitalize()}" already registered'
        if not City.select().where(City.name == city.capitalize()):
            country_id = Country.select().where(Country.code == country).first()
            new_city = City(country=country_id, name=city.capitalize())
            new_city.save()

            user_city = UserCities(user_id=current_user, city_id=new_city)
            user_city.save()

            message = f'City "{city.capitalize()}" just registered and added to your watchlist'
            flash(message)
            return redirect(url_for('weather.index'))

        city_in_db = City.select().where(City.name == city.capitalize()).first()
        user_cities = UserCities.select().where(UserCities.user_id == current_user)
        if city_in_db not in user_cities:
            user_city = UserCities(user_id=current_user, city_id=city_in_db)
            user_city.save()
            message = f'City "{city.capitalize()}" added to your watchlist'

        flash(message)
        return redirect(url_for('weather.index'))
    return redirect(url_for('weather.index'))


@weather.route('/show/cities/<int:page>', methods=['GET'])
@weather.route('/show/cities')
@login_required
def show_cities(page=1):
    """Show all cities."""
    qty_per_page = get_qty_position_per_page()
    cities = City.select()
    country_name = request.args.get('country_name')
    if country_name:
        country = Country.select().where(Country.name == country_name).first()
        if country:
            cities = country.city
            page = 1
    pagination = Pagination(page=page, per_page=qty_per_page, total=cities.count(), record_name='cities')
    cities = list(get_weather_for_cities(cities.paginate(page, qty_per_page)))

    return render_template(
        'weather/show_cities.html',
        title='Show cities',
        cities=cities,
        pagination=pagination,
        add_to_user_list=True
        )


@weather.route('/delete/city', methods=['POST', 'GET'])
@login_required
def delete_city():
    """Delete city from database."""
    if request.method == 'POST':
        message = 'Deleted: '
        selectors = list(map(int, request.form.getlist('selectors')))

        qty_per_page = get_qty_position_per_page()
        total_pages = int(len(City.select())) // qty_per_page
        if not selectors:
            flash('Nothing to delete')
            return redirect(url_for('weather.show_cities'))

        for selector in selectors:
            try:
                city = City.get(City.id == selector)
            except DoesNotExist:
                pass
            else:
                message += f'{city.name}, '
                city.delete_instance()

        current_page = int(request.form.get('page'))
        if int(len(City.select())) % qty_per_page == 0 and (current_page - total_pages == 1):
            current_page -= 1

        flash(message)
        return redirect(url_for('weather.show_cities', page=current_page))


@weather.route('/add/cities', methods=['POST', 'GET'])
@login_required
def add_cities():
    """Generate list of capitals."""
    form = GenerateCapitalsForm()

    if form.validate_on_submit():
        if not City.select():
            data_cities = get_cities_for_5_country()
            for city in data_cities:
                country_id = Country.select().where(Country.code == city['country']).first()

                weather_in_city = getting_weather(city['city_name'], city['country'])
                if 'error' in weather_in_city:
                    pass
                else:
                    city = City(country=country_id, name=city['city_name'].capitalize())
                    try:
                        city.save()
                    except IntegrityError:
                        pass

            flash('Database filled with cities')
        else:
            flash('Database is not empty')

    return redirect(url_for('weather.show_cities'))


@weather.route('/show/capitals/<int:page>', methods=['GET'])
@weather.route('/show/capitals')
@login_required
def show_capitals(page=1):
    """Show all capitals."""
    qty_per_page = get_qty_position_per_page()
    capitals = Capital.select()

    country_name = request.args.get('country_name')
    if country_name:
        country = Country.select().where(Country.name == country_name).first()
        if country:
            capitals = country.capital
            page = 1
    pagination = Pagination(page=page, per_page=qty_per_page, total=capitals.count(), record_name='capitals')
    cities = list(get_weather_for_cities(capitals.paginate(page, qty_per_page)))
    return render_template(
        'weather/show_capitals.html',
        title='Show capitals',
        cities=cities,
        pagination=pagination
        )


@weather.route('/delete/capitals', methods=['POST', 'GET'])
@login_required
def delete_capitals():
    """Delete city from database."""
    if request.method == 'POST':
        message = 'Deleted: '
        selectors = list(map(int, request.form.getlist('selectors')))

        qty_per_page = get_qty_position_per_page()
        total_pages = int(len(Capital.select())) // qty_per_page
        if not selectors:
            flash('Nothing to delete')
            return redirect(url_for('weather.show_capitals'))

        for selector in selectors:
            try:
                city = Capital.get(Capital.id == selector)
            except DoesNotExist:
                pass
            else:
                message += f'{city.name}, '
                city.delete_instance()

        current_page = int(request.form.get('page'))
        if int(len(Capital.select())) % qty_per_page == 0 and (current_page - total_pages == 1):
            current_page -= 1

        flash(message)
        return redirect(url_for('weather.show_capitals', page=current_page))


@weather.route('/add/capitals', methods=['POST', 'GET'])
@login_required
def add_capitals():
    """Generate list of capitals."""
    form = GenerateCapitalsForm()

    if form.validate_on_submit():
        if not Capital.select():
            data_capitals = generate_capitals()

            qty_cities = 0
            while qty_cities < 25:
                capital = data_capitals.pop(randint(1, len(data_capitals) - 1))
                weather_in_capital = getting_weather(capital['capital'])
                if 'error' in weather_in_capital:
                    pass
                else:
                    country_id = Country.select().where(Country.name == capital['country']).first()
                    city = Capital(country=country_id, name=capital['capital'])
                    try:
                        city.save()
                    except IntegrityError:
                        pass
                    qty_cities += 1
            flash('Database filled with capitals')

        else:
            flash('Database is not empty')

    return redirect(url_for('weather.show_capitals'))


@weather.route('/show/forecast/5days/<string:city_name>, <string:country_code>')
@login_required
def show_forecast_5days(city_name, country_code):
    """Show weather forecast for five days for the city."""
    forecast_5d = getting_forecast_5d(city_name, country_code=country_code)
    if 'error' in forecast_5d:
        flash(f"{forecast_5d['error']} - ({city_name.capitalize()}).")
        return redirect(url_for('weather.index'))

    country_name = forecast_5d['country_name']
    forecast = forecast_5d['forecast']
    return render_template(
        'weather/show_forecast_5days.html',
        title='Show forecast for 5 days',
        city_name=city_name,
        country_name=country_name,

app/templates/weather/_table_show.html
<table class="table table-hover table-striped" id="userTable">
    <thead>
        <tr>
            <th scope="col">Select</th>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="text-center">City</th>
            <th scope="col" class="text-center">Country</th>
            <th scope="col" class="text-center">latitude</th>
            <th scope="col" class="text-center">longitude</th>
            <th scope="col" class="text-center">sky</th>
            <th scope="col" class="text-center">temperature</th>
            <th scope="col" class="text-center">wind_speed</th>
            <th scope="col" class="text-center">img</th>
            {% if add_to_user_list%}
                <th scope="col" class="text-center">add to watch list</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for city in cities %}
        <tr>
            <td class="text-center">
                <input type="checkbox" name="selectors" class="checkbox" value="{{ city[0] }}"/></td>
            <td class="text-center">{{ loop.index + pagination.skip }}</td>
            <td class="text-center">
                <a href="{{ url_for('weather.show_forecast_5days',
                 city_name=city[1].city_name,
                  country_code=city[1].country_code) }}">
                    {{ city[1].city_name }}</a>
            </td>
            <td class="text-center">
                <a href="?country_name={{ city[1].country_name }}">
                    {{ city[1].country_name }}
                </a>
            </td>
            <td class="text-center">{{ city[1].latitude }}</td>
            <td class="text-center">{{ city[1].longitude }}</td>
            <td class="text-center">{{ city[1].sky }}</td>
            <td class="text-center">{{ city[1].temperature }}</td>
            <td class="text-center">{{ city[1].wind_speed }}</td>
            <td class="warning text-center">
                <img src="{{ city[1].icon_url }}" alt="{{ city[1].icon_url }}" width="40">
            </td>
            {% if add_to_user_list%}
                <td>
                    {% if current_user in city[2] %}
                        Already on the watchlist
                    {% else %}
                        <a href="{{ url_for('weather.add_city_to_user_list', city_id=city[0]) }}">
                                <button type="button" class="btn btn-info">Add to my list</button>
                            </a>
                    {% endif %}
                 </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>

app/templates/weather/add_city.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>Please add city.</h1>
</div>
{% include 'messages.html' %}

<form action="{{ url_for('weather.add_city') }}" method="POST">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.country) }}
    {{ wtf.form_field(form.city) }}
    {{ wtf.form_field(form.submit) }}
</form>

<hr>

{% endblock page_content %}

app/templates/weather/index.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>Welcome to the application Weather.</h1>
</div>
{% include 'messages.html' %}

{% if  weather %}
<form action="{{ url_for('weather.add_city') }}" method="post" id="userForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="hidden" name="city" value="{{ weather.city_name }}"/>
    <input type="hidden" name="country" value="{{ weather.country_code }}"/>
    <button type="submit" class="btn btn-primary">Add city</button>
</form>

    <table class="table table-hover table-striped" id="userTable">
        <caption>
        </caption>
        <thead>
        <tr>
            <th scope="col" class="text-center">City</th>
            <th scope="col" class="text-center">Country</th>
            <th scope="col" class="text-center">latitude</th>
            <th scope="col" class="text-center">longitude</th>
            <th scope="col" class="text-center">sky</th>
            <th scope="col" class="text-center">temperature</th>
            <th scope="col" class="text-center">wind_speed</th>
            <th scope="col" class="text-center">img</th>
        </tr>

        </thead>
        <tbody>
            <tr>
                <td class="text-center"><a href="https://www.google.com/maps/place/{{ weather.city_name }}/
                @{{ weather.latitude }},{{ weather.longitude }}" target="_blank" rel="noopener noreferrer nofollow">
                    {{ weather.city_name }}</a></td>
                <td class="text-center">{{ weather.country_name }}</td>
                <td class="text-center">{{ weather.latitude }}</td>
                <td class="text-center">{{ weather.longitude }}</td>
                <td class="text-center">{{ weather.sky }}</td>
                <td class="text-center">{{ weather.temperature }}</td>
                <td class="text-center">{{ weather.wind_speed }}</td>
                <td class="warning text-center text-center"><img src="{{ weather.icon_url }}" alt="{{ weather.icon_url }}" width="40"></td>
            </tr>
        </tbody>
    </table>

{% else %}
{% endif %}



<form action="{{ url_for('weather.index') }}" method="POST" id="form">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.city) }}
    {{ wtf.form_field(form.submit, form='form') }}
</form>

<hr>

<p>The local date and time is {{ moment(current_time).format('MMMM Do YYYY, H:mm:ss') }}.</p>
<p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>

{% endblock page_content %}

app/templates/weather/show_capitals.html
{% extends '_base.html' %}


{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>Capitals.</h1>
</div>
{% include 'messages.html' %}


<div class="table-responsive">

    {% if cities %}

    <div style="display: inline;">
        <button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">
            Select all</button>
        <button type="submit" class="btn btn-danger" form="cityForm">
            Delete</button>
        {% include '_go_back.html' %}
    </div>

        <form action="{{ url_for('weather.delete_capitals') }}" method="post" id="cityForm">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="table-responsive">

                {% include 'weather/_table_show.html' %}

            </div>

            <input type="hidden" name="page" value="{{ pagination.page}}">
            <div style="text-align: center;">
                {{ pagination.info}}
                {{ pagination.links }}
            </div>
        </form>

    {% else %}
        <p>You can fill out database.</p>
        <form action="{{ url_for('weather.add_capitals') }}" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type="submit" class="btn btn-primary">Add capitals</button>
        </form>
    {% endif%}
</div>

{% endblock page_content %}

app/templates/weather/show_cities.html
{% extends '_base.html' %}


{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>Cities.</h1>
</div>
{% include 'messages.html' %}


<div class="table-responsive">

    {% if cities %}
    <div style="display: inline;">
        <button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">
            Select all</button>
        <button type="submit" class="btn btn-danger" form="cityForm">
            Delete</button>
        {% include '_go_back.html' %}

    </div>
        <form action="{{ url_for('weather.delete_city') }}" method="post" id="cityForm">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="table-responsive">

                {% include 'weather/_table_show.html' %}

            </div>
            <input type="hidden" name="page" value="{{ pagination.page}}">
            <div style="text-align: center;">
                {{ pagination.info}}
                {{ pagination.links }}
            </div>
        </form>

    {% else %}
        <p>You can fill out database.</p>
        <form action="{{ url_for('weather.add_cities') }}" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type="submit" class="btn btn-primary">Add cities</button>
        </form>
    {% endif%}
</div>

{% endblock page_content %}

app/templates/weather/show_forecast_5days.html
{% extends '_base.html' %}


{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>{{ title }}</h1>
</div>
{% include 'messages.html' %}


<div class="table-responsive">
        {% include '_go_back.html' %}

    <table class="table table-hover table-striped">
            <caption style="font-size: 16px;">Below is the weather forecast for five days for the city of {{ city_name }}
            from the country {{ country_name }}.</caption>
        <thead>
            <tr>
                <th scope="col" class="text-center">img</th>
                <th scope="col" class="text-center">Data</th>
                <th scope="col" class="text-center">Time</th>
                <th scope="col" class="text-center">Temperature</th>
                <th scope="col" class="text-center">Description</th>
                <th scope="col" class="text-center">Clouds</th>
                <th scope="col" class="text-center">Wind_speed</th>
            </tr>
        </thead>
        <tbody>
        {% for date, weather in forecast.items() %}
                    {% for data in weather %}
                        <tr>
                            <td class="warning text-center"><img src="{{ data.icon_url }}" alt="" width="40"></td>
                            <td class="text-center" rowspan="">{{ date }}</td>
                            <td class="text-center">{{ data.time }}</td>
                            <td class="text-center">{{ data.temperature }}</td>
                            <td class="text-center">{{ data.description }}</td>
                            <td class="text-center">{{ data.clouds }}</td>
                            <td class="text-center">{{ data.wind_speed }}</td>
                         </tr>
                {% endfor %}
        {% endfor %}
        </tbody>
    </table>

    <form>
        <input class="btn btn-success" type="button" value="Go back!" onclick="history.back()">
    </form>
</div>

{% endblock page_content %}

app/templates/weather/show_user_cities.html
{% extends '_base.html' %}


{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>{{ current_user.name }}'s cities.</h1>
</div>
{% include 'messages.html' %}


<div class="table-responsive">

    {% if cities %}
    <div style="display: inline;">
        <button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">
            Select all</button>
        <button type="submit" class="btn btn-danger" form="cityForm">
            Delete</button>
        {% include '_go_back.html' %}

    </div>
        <form action="{{ url_for('weather.delete_city') }}" method="post" id="cityForm">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="table-responsive">

                {% include 'weather/_table_show.html' %}

            </div>
            <input type="hidden" name="page" value="{{ pagination.page}}">
            <div style="text-align: center;">
                {{ pagination.info}}
                {{ pagination.links }}
            </div>
        </form>

    {% else %}
        <p>Your watchlist is empty.</p>
    {% endif%}
</div>

{% endblock page_content %}