app/main/models.py
from peewee import *
from app.base_model import BaseModel


class User(BaseModel):
    name = CharField(max_length=100)
    email = CharField(max_length=150, unique=True, index=True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField
from wtforms.validators import DataRequired, Length


class GenerateDataForm(FlaskForm):
    submit = SubmitField('Generate')


class NameForm(FlaskForm):
    name = StringField(
        'What is your name?',
        validators=[DataRequired(), Length(3, 100)],
        render_kw={'placeholder': 'Full name'}
    )
    email = EmailField(
        'What is your email?',
        validators=[DataRequired(), Length(10, 150)],
        render_kw={'placeholder': 'Email'}
    )
    submit = SubmitField('Add')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
"""Routes for app 'main'."""
from flask import render_template, redirect, url_for, flash, request
from datetime import datetime

from flask_login import current_user
from flask_paginate import Pagination
from peewee import DoesNotExist


from app.main import main
from app.main.forms import NameForm, GenerateDataForm
from app.main.models import User
from app.auth.models import UserAuth
from app.handlers.get_qty_position_per_page import get_qty_position_per_page
from utils.generate_data.main import main as generate_data
from utils.generate_data.data import emails_data
from app.auth.utils import check_permissions


@main.route('/')
def start():
    """Start page."""
    try:
        name = current_user.name
    except AttributeError:
        name = None
    return render_template(
        'index.html',
        title='Start page',
        current_time=datetime.utcnow(),
        name=name,
    )


@main.route('/home', methods=['POST', 'GET'])
def index():
    """Home page"""
    form = GenerateDataForm()

    if form.validate_on_submit():
        if not User.select():
            emails = generate_data(emails_data)
            for name, email in emails:
                user = User(name=name, email=email)
                user.save()
            flash('Database filled with test data')
        else:
            flash('Database is not empty')

    return render_template(
        'main/index.html',
        title='Home page',
        current_time=datetime.utcnow(),
        form=form
    )


@main.route('/add/email', methods=['POST', 'GET'])
def add_email():
    """Add name and email form page"""
    form = NameForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        message = f'User with name {name} already registered'
        if not User.select().where(User.email == email):
            user = User(name=name, email=email)
            user.save()
            message = f'User with name {name} just registered'

        flash(message)
        return redirect(url_for('main.add_email'))

    return render_template(
        'main/email.html',
        title='Register user',
        form=form
    )


@main.route('/show/emails/<int:page>', methods=['GET', 'POSR'])
@main.route('/show/emails')
def show_emails(page=1):
    """Show user information"""
    qty_per_page = get_qty_position_per_page()
    users = UserAuth.select()
    pagination = Pagination(page=page, per_page=qty_per_page, total=users.count(), record_name='users')
    users = users.paginate(page, qty_per_page)
    return render_template(
        'main/show_emails.html',
        title='Show users',
        users=users,
        pagination=pagination
        )


@main.route('/delete/emails', methods=['POST'])
def delete_emails():
    """Delete selected users"""
    if not check_permissions(current_user):
        flash('You don\'t have access to do it.', 'error')
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        message = 'Deleted: '
        selectors = list(map(int, request.form.getlist('selectors')))

        if not selectors:
            flash('Nothing to delete')
            return redirect(url_for('main.show_emails'))

        for selector in selectors:
            user = UserAuth.get(UserAuth.id == selector)
            message += f'{user.email} '
            user.delete_instance()

        page = int(request.form.get('page'))
        qty_per_page = get_qty_position_per_page()
        if int(len(UserAuth.select())) % qty_per_page == 0:
            page -= 1

        flash(message)
        return redirect(url_for('main.show_emails', page=page))


@main.route('/update/<user_id>')
def update(user_id):
    """Edit user's data."""
    if not check_permissions(current_user, user_id):
        flash('You don\'t have access to edit this item.', 'error')
        return redirect(url_for('main.index'))

    form = NameForm()
    try:
        user = UserAuth.get(UserAuth.id == user_id)
    except DoesNotExist:
        flash(f'User with id: {user_id} not found. You can add user in this form.')
        return redirect(url_for('main.add_email'))

    else:
        form.name.label.text = 'Edit this name'
        form.email.label.text = 'Edit this email'
        form.submit.label.text = 'Edit'
        return render_template(
            'main/update.html',
            title='Data update',
            form=form,
            user=user
        )


@main.route('/update/edit/<user_id>', methods=['POST', 'GET'])
def edit(user_id):
    """Update user's data."""
    form = NameForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        user = UserAuth.get(UserAuth.id == user_id)

        if email == user.email and name == user.name:
            flash('Users name and email did not change.')
            return redirect(url_for('main.update', user_id=user_id))

        elif email == user.email:
            message = f'User\'s name "{user.name.capitalize()}" for user with id: {user.id}' \
                      f' was changed to "{name.capitalize()}".'
            user.name = name
            user.save()
            flash(message)
            return redirect(url_for('main.show_emails'))

        elif not UserAuth.select().where(UserAuth.email == email):
            user.name = name
            user.email = email
            user.save()
            flash(f"Data for user with id: {user.id} was changed.")
            return redirect(url_for('main.show_emails'))

        message = f'User with email "{email}" already exists.'
        flash(message)
        return redirect(url_for('main.update', user_id=user_id))

app/templates/main/add_email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}

    <div class="page-header">
        <h1>Register user</h1>
    </div>
    {% include 'messages.html' %}
        <form action="{{ url_for('main.add_email') }}" method="POST">
            {{ form.csrf_token }}
            {{ wtf.form_field(form.name) }}
            {{ wtf.form_field(form.email) }}
            {{ wtf.form_field(form.submit) }}
        </form>

{% endblock page_content %}

app/templates/main/email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}

<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<form action="{{ url_for('main.add_email') }}" method="POST">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.name) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.submit) }}
</form>

{% endblock page_content %}

app/templates/main/index.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}

<div class="page-header">
  <h1>Welcome to the application Users.</h1>
</div>

<h3>Generate test data</h3>
{% include 'messages.html' %}
<form action="{{ url_for('main.index') }}" method="post">
  {{ form.csrf_token }}
  {{ wtf.form_field(form.submit) }}
</form>
<hr>

<p>The local date and time is {{ moment(current_time).format('MMMM Do YYYY, H:mm:ss') }}.</p>
<p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>

{% endblock page_content %}

app/templates/main/show_emails.html
{% extends '_base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}

<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="userForm">Delete</button>

<form action="{{ url_for('main.delete_emails') }}" method="post" id="userForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="table-responsive">
        <table class="table table-hover table-striped" id="userTable">
            <thead>
            <tr>
                <th scope="col" class="col-md-1">Select</th>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <input type="checkbox" name="selectors" class="checkbox" value="{{ user.id }}"/></td>
                <td>{{ loop.index + pagination.skip }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="{{ url_for('main.update', user_id=user.id) }}">
                        <button type="button" class="btn btn-info">Edit</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        <input type="hidden" name="page" value="{{ pagination.page}}">
</form>
    <div style="text-align: center;">
        {{ pagination.info}}
        {{ pagination.links }}
    </div>

{% endblock page_content%}

app/templates/main/update.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
        <h1>Edit your data.</h1>
    </div>

    {% include 'messages.html' %}

    <form action="edit/{{ user.id }}" method="POST">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.name, value=user.name) }}
        {{ wtf.form_field(form.email, value=user.email) }}
        {{ wtf.form_field(form.submit) }}
    </form>
{% endblock page_content %}